Algoritmo "Repita"
//Disciplina: [Lógica de Programação]
//Professor: Jailson
//Descrição: apresentação da função Repita.
// Autor(a): Stephany Marciano Dias
// Data atual: 11/09/2023
Var
// Seção de Declarações das variáveis 
 contadora: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
repita
escreval("Jailson", contadora)
contadora<-contadora+1
ate contadora=120

Fimalgoritmo